# Generated by Django 6.0.7 on 2026-09-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendalibre', '0004_producto_activo_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
